<a href="https://colab.research.google.com/github/annazhao1111/LinearAlgebraAndProbability/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
A.append(4)

AttributeError: ignored

In [9]:
L + [5]

[1, 2, 3, 4, 5]

In [10]:
A + np.array([4])

array([5, 6, 7])

In [11]:
A + np.array([4,5,6])

array([5, 7, 9])

In [12]:
A + np.array([4,5])

ValueError: ignored

In [13]:
2 * A

array([2, 4, 6])

In [14]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [16]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [17]:
L2 =[]
for e in L:
  L2.append(e + 3)

In [18]:
L2

[4, 5, 6, 7]

In [19]:
L2 = [e + 3 for e in L]

In [20]:
L2

[4, 5, 6, 7]

In [21]:
L**2

TypeError: ignored

In [22]:
L2 = []
for e in L:
  L2.append(e**2)

In [23]:
L2

[1, 4, 9, 16]

In [24]:
A**2

array([1, 4, 9])

In [25]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [26]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [27]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [28]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [29]:
a = np.array([1,2])
b = np.array([3,4])

In [30]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [31]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [32]:
a * b

array([3, 8])

In [33]:
np.sum(a * b)

11

In [34]:
(a * b).sum()

11

In [35]:
np.dot(a, b)

11

In [36]:
a.dot(b)

11

In [37]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [38]:
amag = np.sqrt((a * a).sum())

In [39]:
amag

2.23606797749979

In [40]:
np.linalg.norm(a)

2.23606797749979

In [41]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [42]:
cosangle

0.9838699100999074

In [43]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Matrices

In [44]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [45]:
L[0][1]

2

In [46]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [47]:
A[0][1]

2

In [48]:
A[0,1]

2

In [49]:
A[:,0]

array([1, 3])

In [50]:
A.T

array([[1, 3],
       [2, 4]])

In [51]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [52]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [53]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
 A

array([[1, 2],
       [3, 4]])

In [55]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [56]:
A.dot(B.T)

ValueError: ignored

In [57]:
np.linalg.det(A)

-2.0000000000000004

In [58]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [59]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [60]:
np.trace(A)

5

In [61]:
np.diag(A)

array([1, 4])

In [62]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [63]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [64]:
Lam, V = np.linalg.eig(A)

In [66]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [67]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [68]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [69]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems