<a href="https://colab.research.google.com/github/annazhao1111/LinearAlgebraAndProbability/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array vs Lists

In [1]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

In [ ]:
A.append(4)

AttributeError: ignored

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

In [ ]:
A + np.array([4])

array([5, 6, 7])

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

In [ ]:
A + np.array([4,5])

ValueError: ignored

In [ ]:
2 * A

array([2, 4, 6])

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
L2 =[]
for e in L:
  L2.append(e + 3)

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

[4, 5, 6, 7]

In [ ]:
L**2

TypeError: ignored

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

[1, 4, 9, 16]

In [ ]:
A**2

array([1, 4, 9])

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [ ]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [ ]:
a * b

array([3, 8])

In [ ]:
np.sum(a * b)

11

In [ ]:
(a * b).sum()

11

In [ ]:
np.dot(a, b)

11

In [ ]:
a.dot(b)

11

In [ ]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [ ]:
amag = np.sqrt((a * a).sum())

In [ ]:
amag

2.23606797749979

In [ ]:
np.linalg.norm(a)

2.23606797749979

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [ ]:
cosangle

0.9838699100999074

In [ ]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Matrices

In [ ]:
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [ ]:
L[0][1]

2

In [ ]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [ ]:
A[0][1]

2

In [ ]:
A[0,1]

2

In [ ]:
A[:,0]

array([1, 3])

In [ ]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
 A

array([[1, 2],
       [3, 4]])

In [ ]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
A.dot(B.T)

ValueError: ignored

In [ ]:
np.linalg.det(A)

-2.0000000000000004

In [ ]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [ ]:
np.trace(A)

5

In [ ]:
np.diag(A)

array([1, 4])

In [ ]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [ ]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [ ]:
V[:,0] * Lam[0], A @ V[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

True

## Solving Linear Systems

In [2]:
A = np.array([[1,1],[1.5,4]])
b = np.array([2200, 5050])

In [3]:
np.linalg.solve(A,b)

array([1500.,  700.])

## Generating Data

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.random.random()

0.7765004223980793

In [9]:
np.random.random((2,3))

array([[0.41692478, 0.35819881, 0.80264338],
       [0.80246427, 0.4506438 , 0.07418758]])

In [10]:
np.random.randn(2,3)

array([[-0.4187558 ,  1.50664407, -0.33907709],
       [-0.30405464, -0.34105361, -0.31261531]])

In [11]:
R = np.random.randn(10000)

In [12]:
R.mean()

0.006976538353281003

In [13]:
np.mean(R)

0.006976538353281003

In [14]:
R.var()

0.9734453262127134

In [15]:
R.std()

0.9866333291617071

In [16]:
R = np.random.randn(10000,3)

In [17]:
R.mean(axis=0)

array([-0.00264133,  0.01346163, -0.00367665])

In [18]:
R.mean(axis=1)

array([ 0.05761946, -0.130735  ,  0.54367407, ...,  0.11460245,
        0.46302864, -0.91414407])

In [19]:
R.mean(axis=1).shape

(10000,)

In [20]:
np.cov(R)

array([[ 0.28603259, -0.03890022, -0.85854369, ..., -0.14616083,
         0.13357496, -0.05671661],
       [-0.03890022,  0.00558768,  0.12883261, ...,  0.03322195,
        -0.02568061,  0.01958865],
       [-0.85854369,  0.12883261,  3.06714323, ...,  0.98057095,
        -0.70607124,  0.65244978],
       ...,
       [-0.14616083,  0.03322195,  0.98057095, ...,  0.67368496,
        -0.40556971,  0.56204069],
       [ 0.13357496, -0.02568061, -0.70607124, ..., -0.40556971,
         0.25233005, -0.32666781],
       [-0.05671661,  0.01958865,  0.65244978, ...,  0.56204069,
        -0.32666781,  0.48562488]])

In [21]:
np.cov(R).shape

(10000, 10000)

In [22]:
np.cov(R.T)

array([[ 0.98972506,  0.00843554, -0.00650903],
       [ 0.00843554,  0.99050348,  0.004149  ],
       [-0.00650903,  0.004149  ,  1.01298296]])

In [23]:
np.cov(R, rowvar=False)

array([[ 0.98972506,  0.00843554, -0.00650903],
       [ 0.00843554,  0.99050348,  0.004149  ],
       [-0.00650903,  0.004149  ,  1.01298296]])

In [24]:
np.random.randint(0,10,size=(3,3))

array([[5, 1, 1],
       [2, 2, 5],
       [8, 5, 2]])

In [25]:
np.random.choice(10,size=(3,3))

array([[4, 6, 2],
       [7, 2, 6],
       [6, 3, 0]])